# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f18a7ecc490276f2ce558c43734ca08d8bdb1dd1e92f436fe1631aa9d2c94c3cab2b525443e1e67322bb61d6b06ba1b39aa93884fd29f8fde22809295e6b53e
  AWS_ACCESS_KEY_ID: AKIAIFSU6DMUNTNOO4BA
  AWS_SECRET_ACCESS_KEY: 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
  AWS_REGION: 'us-west-2'
  S3_BUCKET: tootoo
test:
  secret_key_base: 6405d299e7d2bccf58012157ef9fce0aa8cd28628da723084605098e4e68a16e9c898ea3f48e9c19eb32961e615fcfa79823738adb34636086a9c801e21dd93e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
